import type { Metadata } from "next";
import { Abel, Playfair_Display } from "next/font/google";
import localFont from "next/font/local";

import "the-new-css-reset/css/reset.css";
import "@/app/styles/globals.css";

const abel = Abel({
  weight: "400",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  style: "italic",
});
const bedini = localFont({
  src: "../public/fonts/Bedini/Bedini-Bold-Italic.ttf.woff",
});

const maruburi = localFont({
  src: "../public/fonts/MaruBuri/MaruBuri-Regular.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.className} ${bedini.className} ${maruburi.className} ${abel.className}`}
      >
        {children}
      </body>
    </html>
  );
}
